"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Sparkles, Send, Camera as InstagramIcon, Clock, Heart, MessageCircle, Share2, Copy, Mail } from "lucide-react";
import { motion } from "framer-motion";
import toast from "react-hot-toast";

// Mock Data
const MOCK_QUEUE = [
  { id: 1, filename: "RD_Model_A.jpg", time: "Today, 18:00", caption: "Check out our latest architectural scale model for the downtown project! #RDModels #Architecture" },
];

const MOCK_HISTORY = [
  { id: 101, filename: "RD_Model_Past.jpg", date: "May 20, 2026", likes: 342, comments: 12 },
  { id: 102, filename: "RD_Model_Old.jpg", date: "May 15, 2026", likes: 512, comments: 24 },
];

export default function InstagramPage() {
  const [isConnected, setIsConnected] = useState(false);
  const [caption, setCaption] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [autoCaption, setAutoCaption] = useState(true);
  const [isShareOpen, setIsShareOpen] = useState(false);

  const handleCopyCaption = () => {
    if (!caption) {
      toast.error("Please write a caption first!");
      return;
    }
    navigator.clipboard.writeText(caption);
    toast.success("Caption copied to clipboard!");
  };

  const handleSystemShare = async () => {
    if (!caption) {
      toast.error("Please write a caption first!");
      return;
    }
    if (typeof navigator !== "undefined" && navigator.share) {
      try {
        await navigator.share({
          title: "New Post Review",
          text: caption,
        });
        toast.success("Shared successfully!");
      } catch (error) {
        console.error("Error sharing:", error);
      }
    } else {
      navigator.clipboard.writeText(caption);
      toast.success("System share not supported. Caption copied to clipboard!");
    }
  };

  const handleShareWhatsAppContact = (phone, name) => {
    if (!caption) {
      toast.error("Please write a caption first!");
      return;
    }
    const url = `https://api.whatsapp.com/send?phone=91${phone}&text=${encodeURIComponent(`Hi ${name}, here is the new post for review:\n\n` + caption)}`;
    window.open(url, "_blank");
    toast.success(`Opening WhatsApp chat with ${name}...`);
  };

  const handleConnect = () => {
    // Simulate OAuth flow
    toast.success("Redirecting to Instagram Auth...");
    setTimeout(() => {
      setIsConnected(true);
      toast.success("Successfully connected to RD Models Instagram!");
    }, 1500);
  };

  const generateCaption = async () => {
    setIsGenerating(true);
    // Simulate AI API call
    await new Promise(resolve => setTimeout(resolve, 1500));
    setCaption("Experience precision and elegance with our newest architectural scale model. Every detail crafted to perfection. 🏢✨\n\n#RDModels #Architecture #ScaleModel #Design #RealEstate");
    setIsGenerating(false);
    toast.success("Caption generated by AI!");
  };

  return (
    <div className="space-y-5 max-w-6xl mx-auto pb-12">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Instagram Studio</h1>
          <p className="text-[13px] text-muted-foreground mt-0.5">Manage posting, auto-captions, and view history.</p>
        </div>
        
        {!isConnected ? (
          <Button onClick={handleConnect} className="bg-pink-600 hover:bg-pink-700 text-white shadow-md transition-transform active:scale-95">
            <InstagramIcon className="w-5 h-5 mr-2" />
            Connect Account
          </Button>
        ) : (
          <div className="flex items-center gap-2 bg-success/10 text-success px-4 py-2 rounded-lg font-medium border border-success/20">
            <CheckCircle2 className="w-5 h-5" />
            Connected as @rdmodels
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        {/* Composer */}
        <div className="space-y-5">
          <div className="bg-card p-4.5 rounded-xl border border-border shadow-sm">
            <h2 className="text-base font-semibold mb-4">Create Post</h2>
            
            <div className="mb-4 aspect-square bg-muted rounded-lg border border-border flex items-center justify-center overflow-hidden">
               <img src="https://picsum.photos/seed/composer/600/600" alt="Preview" className="w-full h-full object-cover" />
            </div>

            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <Switch id="auto-caption" checked={autoCaption} onCheckedChange={setAutoCaption} />
                  <Label htmlFor="auto-caption">Use AI Auto-Caption</Label>
                </div>
                <Button 
                  variant="outline" 
                  size="sm" 
                  onClick={generateCaption} 
                  disabled={isGenerating || !autoCaption}
                  className="text-accent border-accent/30 hover:bg-accent/10 hover:text-accent"
                >
                  {isGenerating ? (
                    <div className="w-4 h-4 mr-2 border-2 border-accent/30 border-t-accent rounded-full animate-spin" />
                  ) : (
                    <Sparkles className="w-4 h-4 mr-2" />
                  )}
                  Generate
                </Button>
              </div>

              <div className="relative">
                <Textarea 
                  placeholder="Write your caption here..." 
                  className="min-h-[120px] resize-none"
                  value={caption}
                  onChange={(e) => setCaption(e.target.value)}
                />
                <div className="absolute bottom-2 right-2 text-xs text-muted-foreground">
                  {caption.length}/2200
                </div>
              </div>

              <div className="flex gap-2 pt-2">
                <Button className="flex-1 bg-primary hover:bg-primary/90 text-white text-xs h-9" disabled={!isConnected}>
                  <Send className="w-3.5 h-3.5 mr-1" /> Post Now
                </Button>
                <Button className="flex-1 bg-secondary text-secondary-foreground hover:bg-secondary/90 text-xs h-9" disabled={!isConnected}>
                  <Clock className="w-3.5 h-3.5 mr-1" /> Schedule
                </Button>
                <Button 
                  type="button"
                  variant="outline"
                  className="flex-1 border-neutral-300 dark:border-neutral-700 hover:bg-neutral-50 dark:hover:bg-neutral-900 text-xs h-9 gap-1 text-foreground font-semibold shadow-sm transition-all"
                  onClick={() => setIsShareOpen(true)}
                >
                  <Share2 className="w-3.5 h-3.5 text-neutral-600 dark:text-neutral-400" /> Share
                </Button>
              </div>
            </div>
          </div>
        </div>

        {/* Queue & History */}
        <div className="space-y-5">
          <div className="bg-card p-4.5 rounded-xl border border-border shadow-sm">
            <h2 className="text-base font-semibold mb-3 flex items-center gap-2">
              <Clock className="w-4.5 h-4.5 text-primary" /> Upcoming Queue
            </h2>
            <div className="space-y-3">
              {MOCK_QUEUE.map(item => (
                <div key={item.id} className="flex gap-4 p-3 rounded-lg border border-border bg-background hover:bg-muted/50 transition-colors">
                  <img src="https://picsum.photos/seed/queue/100/100" alt="Queue" className="w-16 h-16 rounded object-cover" />
                  <div className="flex-1 min-w-0">
                    <div className="flex justify-between items-start">
                      <h4 className="font-medium text-sm truncate">{item.filename}</h4>
                      <span className="text-xs font-semibold text-info bg-info/10 px-2 py-0.5 rounded">{item.time}</span>
                    </div>
                    <p className="text-xs text-muted-foreground mt-1 line-clamp-2">{item.caption}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-card p-4.5 rounded-xl border border-border shadow-sm">
            <h2 className="text-base font-semibold mb-3 flex items-center gap-2">
              <InstagramIcon className="w-4.5 h-4.5 text-pink-500" /> Recent Posts
            </h2>
            <div className="space-y-3">
              {MOCK_HISTORY.map(item => (
                <div key={item.id} className="flex gap-4 p-3 rounded-lg border border-border bg-background hover:bg-muted/50 transition-colors">
                  <img src={`https://picsum.photos/seed/${item.id}/100/100`} alt="History" className="w-16 h-16 rounded object-cover grayscale-[30%]" />
                  <div className="flex-1 min-w-0 flex flex-col justify-center">
                    <div className="flex justify-between items-start mb-2">
                      <h4 className="font-medium text-sm truncate">{item.filename}</h4>
                      <span className="text-xs text-muted-foreground">{item.date}</span>
                    </div>
                    <div className="flex gap-4 text-xs font-medium text-muted-foreground">
                      <span className="flex items-center gap-1"><Heart className="w-3.5 h-3.5" /> {item.likes}</span>
                      <span className="flex items-center gap-1"><MessageCircle className="w-3.5 h-3.5" /> {item.comments}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Share Modal */}
      <Dialog open={isShareOpen} onOpenChange={setIsShareOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-base font-semibold">
              <Share2 className="w-4.5 h-4.5 text-primary" />
              Share Post & Caption
            </DialogTitle>
          </DialogHeader>
          
          <div className="space-y-4 py-3">
            {/* Post Preview Card */}
            <div className="border border-border rounded-lg p-3 bg-muted/30 flex gap-3.5">
              <img 
                src="https://picsum.photos/seed/composer/100/100" 
                alt="Post Preview" 
                className="w-16 h-16 rounded object-cover flex-shrink-0"
              />
              <div className="flex-1 min-w-0">
                <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-1">Caption Preview</p>
                <p className="text-xs text-foreground line-clamp-3 italic">
                  {caption || "No caption written yet..."}
                </p>
              </div>
            </div>

            {/* Sharing Methods */}
            <div className="space-y-3">
              {/* Native System Share */}
              <div className="space-y-1.5">
                <span className="text-[11px] font-bold text-muted-foreground uppercase tracking-wider block">System Share</span>
                <Button 
                  onClick={handleSystemShare} 
                  className="w-full bg-primary hover:bg-primary/90 text-white gap-2 text-xs font-semibold h-9"
                >
                  <Share2 className="w-3.5 h-3.5" />
                  Share via Apps (Open System Dialog)
                </Button>
              </div>

              <div className="h-px bg-border my-2" />

              {/* Direct Contacts */}
              <div className="space-y-2">
                <span className="text-[11px] font-bold text-muted-foreground uppercase tracking-wider block">Send directly on WhatsApp</span>
                
                {/* Yogendra Yogi */}
                <Button 
                  onClick={() => handleShareWhatsAppContact("8302829465", "Yogendra Yogi")} 
                  className="w-full bg-[#25D366] hover:bg-[#25D366]/90 text-white gap-2 text-xs font-semibold h-9 flex items-center justify-center"
                >
                  <svg className="w-4 h-4 fill-current flex-shrink-0" viewBox="0 0 24 24">
                    <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946C.06 5.348 5.397.01 12.008.01c3.202.001 6.212 1.246 8.477 3.514 2.266 2.268 3.507 5.28 3.505 8.484-.004 6.657-5.34 11.997-11.953 11.997-2.005-.001-3.973-.502-5.724-1.455L0 24zm6.27-5.32c1.666.989 3.32 1.48 4.905 1.48 5.27 0 9.554-4.286 9.557-9.56.002-2.553-1.002-4.955-2.829-6.78-1.826-1.824-4.254-2.827-6.808-2.827-5.277 0-9.565 4.286-9.569 9.562-.002 1.625.438 3.213 1.272 4.622l-1.012 3.693 3.822-.987zm11.758-5.385c-.328-.162-1.933-.949-2.228-1.055-.297-.11-.513-.162-.73.162-.216.324-.838 1.055-1.025 1.274-.189.217-.378.243-.705.082-.328-.162-1.383-.509-2.63-1.622-.972-.867-1.628-1.939-1.819-2.264-.19-.324-.02-.5-.184-.66-.147-.145-.328-.379-.492-.569-.164-.19-.219-.324-.328-.541-.108-.217-.053-.405-.027-.568.027-.162.216-.513.324-.676.11-.162.148-.27.223-.405.074-.135.037-.253.018-.405-.018-.152-.216-.513-.3-.714-.083-.205-.185-.175-.258-.178l-.223-.002c-.22 0-.578.082-.88.411-.303.33-1.157 1.129-1.157 2.753 0 1.624 1.189 3.193 1.35 3.41.162.217 2.34 3.57 5.669 5.003.791.341 1.41.544 1.892.7.795.252 1.519.215 2.091.129.639-.096 1.933-.789 2.202-1.55.269-.761.269-1.412.19-1.55-.078-.138-.27-.22-.596-.381z"/>
                  </svg>
                  Yogendra Yogi (8302829465)
                </Button>

                {/* Coordinator */}
                <Button 
                  onClick={() => handleShareWhatsAppContact("7733004347", "Coordinator (Mobile 5)")} 
                  className="w-full bg-[#25D366] hover:bg-[#25D366]/90 text-white gap-2 text-xs font-semibold h-9 flex items-center justify-center"
                >
                  <svg className="w-4 h-4 fill-current flex-shrink-0" viewBox="0 0 24 24">
                    <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946C.06 5.348 5.397.01 12.008.01c3.202.001 6.212 1.246 8.477 3.514 2.266 2.268 3.507 5.28 3.505 8.484-.004 6.657-5.34 11.997-11.953 11.997-2.005-.001-3.973-.502-5.724-1.455L0 24zm6.27-5.32c1.666.989 3.32 1.48 4.905 1.48 5.27 0 9.554-4.286 9.557-9.56.002-2.553-1.002-4.955-2.829-6.78-1.826-1.824-4.254-2.827-6.808-2.827-5.277 0-9.565 4.286-9.569 9.562-.002 1.625.438 3.213 1.272 4.622l-1.012 3.693 3.822-.987zm11.758-5.385c-.328-.162-1.933-.949-2.228-1.055-.297-.11-.513-.162-.73.162-.216.324-.838 1.055-1.025 1.274-.189.217-.378.243-.705.082-.328-.162-1.383-.509-2.63-1.622-.972-.867-1.628-1.939-1.819-2.264-.19-.324-.02-.5-.184-.66-.147-.145-.328-.379-.492-.569-.164-.19-.219-.324-.328-.541-.108-.217-.053-.405-.027-.568.027-.162.216-.513.324-.676.11-.162.148-.27.223-.405.074-.135.037-.253.018-.405-.018-.152-.216-.513-.3-.714-.083-.205-.185-.175-.258-.178l-.223-.002c-.22 0-.578.082-.88.411-.303.33-1.157 1.129-1.157 2.753 0 1.624 1.189 3.193 1.35 3.41.162.217 2.34 3.57 5.669 5.003.791.341 1.41.544 1.892.7.795.252 1.519.215 2.091.129.639-.096 1.933-.789 2.202-1.55.269-.761.269-1.412.19-1.55-.078-.138-.27-.22-.596-.381z"/>
                  </svg>
                  Office Coordinator (7733004347)
                </Button>
              </div>

              <div className="h-px bg-border my-2" />

              {/* Other Options */}
              <div className="space-y-1.5">
                <span className="text-[11px] font-bold text-muted-foreground uppercase tracking-wider block">Other Options</span>
                <div className="grid grid-cols-2 gap-2">
                  <Button 
                    onClick={handleCopyCaption} 
                    variant="outline"
                    className="gap-1.5 text-xs font-semibold h-9"
                  >
                    <Copy className="w-3.5 h-3.5" />
                    Copy Caption
                  </Button>
                  <a 
                    href={`mailto:?subject=New Instagram Post Ready&body=Hi Manager,%0D%0A%0D%0APlease review this new post:%0D%0A%0D%0A${typeof window !== 'undefined' ? encodeURIComponent(caption) : ''}`}
                    className="w-full"
                  >
                    <Button 
                      variant="outline"
                      className="w-full gap-1.5 text-xs font-semibold h-9"
                    >
                      <Mail className="w-3.5 h-3.5" />
                      Email Caption
                    </Button>
                  </a>
                </div>
              </div>
            </div>
          </div>
          
          <DialogFooter className="sm:justify-start">
            <Button 
              type="button" 
              variant="ghost" 
              onClick={() => setIsShareOpen(false)}
              className="text-xs h-8"
            >
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

function CheckCircle2(props) {
  return (
    <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  );
}
